name: Build CI/CD
on:
    push:
    workflow_dispatch:

jobs:
    create-template:
        name: "create template"
        runs-on: ubuntu-latest

        steps:
            - name: <Checkout> Repository
              uses: actions/checkout@v4
              with:
                submodules: 'true'

            - name: <Add> Node/NPM
              uses: actions/setup-node@v4
              with:
                node-version-file: Pe/.node-version
    
            - name: <Setup> NPM
              shell: bash
              run: |
                cd Pe
                npm ci
    
            - name: <Build> template
              shell: bash
              run: |
                cd Pe
                npm run archive:plugin-template
    
            - name: <Artifact> template
              uses: actions/upload-artifact@v4
              with:
                name: plugin-template
                path: Pe/Source/Help/archives/plugin-template.zip
                if-no-files-found: error

    test-template:
        name: "test template"
        needs:
            - create-template
        runs-on: windows-latest

        steps:
            - name: <Download> template
              uses: actions/download-artifact@v4
              with:
                name: plugin-template
                path: artifacts/plugin-template

            - name: <Expand> template
              shell: pwsh
              run: |
                Expand-Archive -Path artifacts/plugin-template/plugin-template.zip -DestinationPath plugin-template
                cd plugin-template
                ls


            - name: <Setup> template
              shell: pwsh
              run: |
                .\plugin-template\create-project.ps1 -ProjectDirectory \test-plugin -PluginId 00000000-0000-0000-0000-000000000000 -PluginName Test.Plugin -DefaultNamespace Test.Plugin
                cd \test-plugin
                ls


