name: Build CI/CD
on:
    push:
      branches-ignore:
        - TEST
    workflow_dispatch:

jobs:
    create-template:
        name: "create template"
        runs-on: ubuntu-latest

        steps:
            - name: <Checkout> Repository
              uses: actions/checkout@v4
              with:
                repository: sk-0520/Pe
                ref: refs/heads/master
                path: Pe

            - name: <Setup> NPM
              shell: bash
              run: ls

            - name: <Add> Node/NPM
              uses: actions/setup-node@v4
              with:
                node-version-file: Pe/.node-version
    
            - name: <Setup> NPM
              shell: bash
              run: |
                cd Pe
                npm ci
    
            - name: <Build> template
              shell: bash
              run: |
                cd Pe
                npm run archive:plugin-template
    
            - name: <Artifact> template
              uses: actions/upload-artifact@v4
              with:
                name: plugin-template
                path: Pe/Source/Help/archives/plugin-template.zip
                if-no-files-found: error

    test-template:
        name: "test template"
        needs:
            - create-template
        runs-on: windows-latest

        steps:
            - name: <Setup> GIT
              shell: pwsh
              run: |
                git config --global core.autoCRLF false
                git config --global user.email ${{ github.actor }}@users.noreply.github.com
                git config --global user.name "${{ github.actor }}"

            - name: <Checkout> Repository
              uses: actions/checkout@v4

            - name: <Download> template
              uses: actions/download-artifact@v4
              with:
                name: plugin-template
                path: artifacts/plugin-template

            - name: <Expand> template
              shell: pwsh
              run: |
                Expand-Archive -Path artifacts/plugin-template/plugin-template.zip -DestinationPath plugin-template
                cd plugin-template
                ls

            - name: <Initialize> template
              shell: pwsh
              run: |
                .\plugin-template\create-project.ps1 -ProjectDirectory \test-plugin -PluginId 00000000-0000-0000-0000-000000000000 -PluginName Test.Plugin -DefaultNamespace Test.Plugin
                ls \test-plugin

            - name: <Setup> template
              shell: pwsh
              run: |
                git checkout -b TEST
                git rm -r .github/workflows/build.yml
                Copy-Item -Path \test-plugin\* -Destination . -Recurse -Force -Exclude @('.git','Pe')
                git add *
                git commit -m "TEST"
                #git push
                ls

            - name: <Artifact> template
              uses: actions/upload-artifact@v4
              with:
                name: plugin-test
                path: .
  