name: workflow_dispatch
on:
    workflow_dispatch:
        inputs:
            PE_REVISION:
                type: string
                required: true
                description: 'Pe SHA1'

permissions:
    contents: write
    pull-requests: write

jobs:
    job:
        name: workflow_dispatch
        uses: ./.github/workflows/_setup-template.yml
        with:
            PE_REVISION: ${{ inputs.PE_REVISION }}

