name: workflow_dispatch
on:
    workflow_dispatch:
      inputs:
        PE_REVISION:
          type: string
          required: true
          description: 'Pe SHA1'

permissions:
    contents: write
    pull-requests: write

concurrency:
    group: ${{ github.ref }}
    cancel-in-progress: true

jobs:
    push:
        name: use
        uses: ./.github/workflows/_setup-template.yml
        with:
            PE_REVISION: ${{ inputs.PE_REVISION }}

